#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
# Verbosity and settings that you pretty much just always are going to want.
alias \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	cp="cp -iv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="pipe-viewer" \
	sdn="doas shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	pac="doas pacman" \
	pu="doas pacman -Syu" \
	yu="yay -Syu --aur" \
	xi="doas xbps-install" \
	xr="doas xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	scrcpy="scrcpy --shortcut-mod=lctrl" \
	ixpe="cd $HOME/Projects/IXPE_Analysis && source .ixpe/bin/activate && clear && ls" \
	foc="cd $HOME/Projects/FOC_Reduction && source .foc/bin/activate && clear && ls" \
	mcmc="cd $HOME/Projects/SimLens && source .mcmc/bin/activate && clear && ls" \
    P="cd $HOME/Documents/LaTeX/Papers/MIR_lensing/ && nvim ."\
	dsu="cd $HOME/Projects/dsutils && source .dsu/bin/activate && clear && ls" \
    config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME" \
	hlup="wg-quick up homelab" \
	hldown="wg-quick down homelab"
