#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# Autostart Pulseaudio if installed and not already started by init.
# Chromium/Brave doesn't automatically start Pulse for some reason.
# [ -x /usr/bin/pulseaudio ] &&
# 	! pidof pulseaudio >/dev/null &&
# 	setsid -f pulseaudio --start >/dev/null 2>&1

remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
mpd &			# music player daemon-you might prefer it as a service though
dunst &			# dunst for notifications
unclutter &     # Remove mouse when idle
xcompmgr &		# xcompmgr for transparency
# setxkbmap fr & 		# set the keyboard layout to azerty (comment out if set in /etc/X11/xorg.conf.d/00-keyboard.conf)
# redshift &		# adjust screen temperature based on daytime
. $HEADAS/headas-init.sh	# set XSPEC into PATH
