# See: /usr/share/doc/mpd/mpdconf.example
music_directory     "/media/Music"
# Recommended location for database
log_file            "/home/drilbl/.config/mpd/logs/mpd.log"
db_file             "/home/drilbl/.config/mpd/mpd.db"
playlist_directory  "/home/drilbl/.config/mpd/playlists"
state_file          "/home/drilbl/.config/mpd/mpd.state"
pid_file            "/home/drilbl/.config/mpd/mpd.pid"

auto_update         "yes"
bind_to_address     "127.0.0.1"
restore_paused      "yes"
max_output_buffer_size "16384"

# Input
input {
    plugin  "curl"
}

# PipeWire output
audio_output {
    type    "pipewire"
    name    "PipeWire Sound Server"
}

audio_output {
    type	"fifo"
    name	"Visualizer feed"
    path	"/tmp/mpd.fifo"
    format	"44100:16:2"
}
